1
1.1
```{r}
student_1 <- c(50.4,62.3,92.1,77.6,TRUE)
student_2 <- c(41.7,87.9,75.3,72.4,FALSE)
student_3 <- c(30.3,67.8,69.3,71.2,FALSE)
student_4 <- c(65.4,85.1,92.3,96.8,TRUE)
student_5 <- c(70.4,88.2,95.2,90.7,TRUE)
```

1.2
```{r}
students_vector <- c(student_1,student_2,student_3,student_4,student_5)
```

1.3

```{r}
students_matrix <- matrix(students_vector, byrow=TRUE, nrow=5)
```
2.
2.1

```{r}
name_students <- c("Lily Brown","Davis Moore","Susan Taylor", "Mike Jones","Tom Hill")
name_courses_legal_age <- c("TIC", "Accounting", "Psychology", "Ethics","Legal_age")
```

2.2

```{r}
colnames(students_matrix) <- name_courses_legal_age
rownames(students_matrix) <- name_students
```

3.
3.1

```{r}
total_grade_student <-rowSums(students_matrix[,c(1,2,3,4)])
```
3.2
```{r}
result_students <- cbind(students_matrix, total_grade_student)
```
4.

```{r}
selected_elements <- students_matrix[c(1,3,5),c(2,4)]
print(selected_elements)
```

5.

5.1

```{r}
students_grades_df <- as.data.frame(result_students)
```

5.2

```{r}
subset(students_grades_df,Accounting>80 & Legal_age==TRUE)
```


6.

6.1, 6.2

```{r}


matrix_function <- function(){
  for (r in 1:nrow(result_students)){
  for (c in 1:(ncol(result_students)-2)) {
    
    print(paste("Fila", r, "y columna",c, "valor", result_students[r,c])) 
    
    if(result_students[r,c]<=45){
       print("Student at risk")
     }else if(result_students[r,c]>45 && result_students[r,c]<61){
       print("Student may be approved")
     }else{
       print("Student approved")
     }
    }
  } 
}

matrix_function()  
     
        
```



7


7.1 
```{r}
index_education <- function(grade) {
  temp <- (1+(grade/100))/2
  return(temp)
}

```
7.2
```{r}
all_students_grade <- students_grades_df[,1:4]
```
7.3
```{r}
lapply(all_students_grade, index_education)
```

8.

```{r}
score_mean <- colMeans(students_grades_df[,1:4])
```

